/*
Navicat MySQL Data Transfer

Source Server         : 192.168.3.2:3306
Source Server Version : 50721
Source Host           : 192.168.3.2:3306
Source Database       : carfl_dev

Target Server Type    : MYSQL
Target Server Version : 50721
File Encoding         : 65001

Date: 2018-04-23 10:32:59
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `user_reso`
-- ----------------------------
DROP TABLE IF EXISTS `user_reso`;
CREATE TABLE `user_reso` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `reso_id` bigint(20) DEFAULT NULL COMMENT '前端配置的资源id',
  `reso_pid` bigint(20) DEFAULT NULL COMMENT '父id',
  `reso_sysname` varchar(200) DEFAULT NULL COMMENT '系统名称',
  `reso_init_name` varchar(200) DEFAULT NULL COMMENT '资源初始名称',
  `reso_name` varchar(200) DEFAULT NULL COMMENT '资源名称',
  `reso_code` varchar(64) DEFAULT NULL COMMENT '资源码',
  `reso_level` int(4) DEFAULT NULL COMMENT '资源级别',
  `reso_status` int(4) DEFAULT NULL COMMENT '状态',
  `reso_path` varchar(500) DEFAULT NULL COMMENT '资源路径',
  `reso_init_icon` varchar(500) DEFAULT NULL COMMENT '资源初始图标',
  `reso_icon` varchar(500) DEFAULT NULL COMMENT '资源图标',
  `reso_type` int(4) DEFAULT NULL COMMENT '资源类型',
  `reso_filetype` int(4) DEFAULT NULL COMMENT '资源文件类型',
  `reso_remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `operator` bigint(20) DEFAULT NULL COMMENT '创建人',
  `operate_time` datetime DEFAULT NULL COMMENT '创建日期',
  `flag` int(4) DEFAULT NULL COMMENT '数据库排序标识',
  `color` varchar(20) DEFAULT NULL,
  `sort` int(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=457 DEFAULT CHARSET=utf8 COMMENT='用户资源管理';

-- ----------------------------
-- Records of user_reso
-- ----------------------------
INSERT INTO `user_reso` VALUES ('1', '1', '69', '指旺汽车金融', '操作人', '操作人', 'operatorName', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('2', '2', '69', '指旺汽车金融', '操作时间', '操作时间', 'operateTime', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('3', '3', '69', '指旺汽车金融', 'mysql文件名', 'mysql文件名', 'mysqlName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('4', '4', '69', '指旺汽车金融', 'mongdb文件名', 'mongdb文件名', 'mongdbName', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('5', '5', '69', '指旺汽车金融', '备份类型', '备份类型', 'type', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('6', '6', '9', '指旺汽车金融', '用户名', '用户名', 'userUsername', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('7', '7', '9', '指旺汽车金融', '姓名', '姓名', 'userRealname', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('8', '8', '9', '指旺汽车金融', '部门', '部门', 'deptName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('9', '9', '9', '指旺汽车金融', '状态', '状态', 'status', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('10', '10', '9', '指旺汽车金融', '电话', '电话', 'userPhone', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('11', '11', '9', '指旺汽车金融', '备注', '备注', 'userRemark', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('12', '12', '9', '指旺汽车金融', '操作人', '操作人', 'operatorName', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('13', '13', '9', '指旺汽车金融', '操作时间', '操作时间', 'operateTime', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('14', '14', '57', '指旺汽车金融', '操作人', '操作人', 'realName', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('15', '15', '57', '指旺汽车金融', '客户端IP', '客户端IP', 'clientIp', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('16', '16', '57', '指旺汽车金融', '执行方法', '执行方法', 'exeMethod', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('17', '17', '57', '指旺汽车金融', '备注', '备注', 'logRemark', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('18', '18', '57', '指旺汽车金融', '请求执行时长（秒）', '请求执行时长（秒）', 'exeTime', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('19', '19', '57', '指旺汽车金融', '执行类型', '执行类型', 'exeType', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('20', '20', '57', '指旺汽车金融', '操作时间', '操作时间', 'operateTime', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('21', '21', '63', '指旺汽车金融', '任务名称', '任务名称', 'jobName', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('22', '22', '63', '指旺汽车金融', '任务所在组', '任务所在组', 'jobGroup', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('23', '23', '63', '指旺汽车金融', '任务描述', '任务描述', 'jobDescribe', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('24', '24', '63', '指旺汽车金融', '任务类名', '任务类名', 'jobClassName', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('25', '25', '63', '指旺汽车金融', '触发器名称', '触发器名称', 'triggerName', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('26', '26', '63', '指旺汽车金融', '触发器所在组', '触发器所在组', 'triggerGroup', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('27', '27', '63', '指旺汽车金融', '下次执行时间', '下次执行时间', 'nextExecutionTime', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('28', '28', '63', '指旺汽车金融', '表达式', '表达式', 'expression', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('29', '29', '63', '指旺汽车金融', '状态', '状态', 'triggerState', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('30', '30', '63', '指旺汽车金融', '时区', '时区', 'timeZone', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('31', '31', '77', '指旺汽车金融', '参数代码', '参数代码', 'paramCode', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('32', '32', '77', '指旺汽车金融', '参数名称', '参数名称', 'paramName', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('33', '33', '77', '指旺汽车金融', '参数值', '参数值', 'paramValue', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('34', '34', '77', '指旺汽车金融', '是否启用', '是否启用', 'paramStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('35', '35', '77', '指旺汽车金融', '说明', '说明', 'paramRemark', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('36', '36', '20', '指旺汽车金融', '状态', '状态', 'roleStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('37', '37', '20', '指旺汽车金融', '角色名称', '角色名称', 'roleName', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('38', '38', '20', '指旺汽车金融', '备注', '备注', 'roleRemark', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('39', '39', '20', '指旺汽车金融', '操作人', '操作人', 'realName', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('40', '40', '20', '指旺汽车金融', '创建时间', '创建时间', 'operateTime', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('41', '41', '34', '指旺汽车金融', '资源初始化名称', '资源初始化名称', 'resoInitName', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('42', '42', '34', '指旺汽车金融', '资源名称', '资源名称', 'resoName', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('43', '43', '34', '指旺汽车金融', '资源初始化图标', '资源初始化图标', 'resoInitIcon', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('44', '44', '34', '指旺汽车金融', '资源图标', '资源图标', 'resoIcon', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('45', '45', '34', '指旺汽车金融', '重置', '重置', 'moduleId', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('46', '46', '34', '指旺汽车金融', '状态', '状态', 'resoStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('47', '47', '34', '指旺汽车金融', '备注', '备注', 'resoRemark', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('48', '48', '109', '指旺汽车金融', '类型', '类型', 'type', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('49', '49', '109', '指旺汽车金融', '一级', '一级', 'first', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('50', '50', '109', '指旺汽车金融', '二级', '二级', 'second', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('51', '51', '109', '指旺汽车金融', 'CRC编码', 'CRC编码', 'crc', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('52', '52', '109', '指旺汽车金融', '详细内容', '详细内容', 'detail', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('53', '53', '109', '指旺汽车金融', '创建人', '创建人', 'operator', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('54', '54', '109', '指旺汽车金融', '创建时间', '创建时间', 'operatorTime', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('55', '55', '175', '指旺汽车金融', '公司简称', '公司简称', 'companyChinaname', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('56', '56', '175', '指旺汽车金融', '省份', '省份', 'companyProvince', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('57', '57', '175', '指旺汽车金融', '城市', '城市', 'companyCity', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('58', '58', '175', '指旺汽车金融', '户名', '户名', 'bankAccount', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('59', '59', '175', '指旺汽车金融', '开户银行', '开户银行', 'depositBank', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('60', '60', '175', '指旺汽车金融', '银行卡号', '银行卡号', 'cardNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('61', '61', '175', '指旺汽车金融', '0', '支行名称', 'branchName', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('62', '62', '175', '指旺汽车金融', '状态', '状态', 'companyStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('63', '63', '144', '指旺汽车金融', '名称', '名称', 'name', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('64', '64', '144', '指旺汽车金融', '是否必传', '是否必传', 'isNecessary', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('65', '65', '108', '指旺汽车金融', '名称', '名称', 'name', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('66', '66', '154', '指旺汽车金融', '产品包名称', '产品包名称', 'productPackageName', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('67', '67', '154', '指旺汽车金融', '经销商', '经销商', 'quotationName', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('68', '68', '154', '指旺汽车金融', '品牌', '品牌', 'carBrandName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('69', '69', '154', '指旺汽车金融', '系列', '系列', 'carSeriesName', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('70', '70', '154', '指旺汽车金融', '型号', '型号', 'carName', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('71', '71', '154', '指旺汽车金融', '颜色', '颜色', 'carColor', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('72', '72', '154', '指旺汽车金融', '市场指导价', '市场指导价', 'marketGuidingPrice', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('73', '73', '154', '指旺汽车金融', '经销商价格', '经销商价格', 'dealerGuidingPrice', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('74', '74', '154', '指旺汽车金融', '首期金额', '首期金额', 'firstPayment', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('75', '75', '154', '指旺汽车金融', '融资金额', '融资金额', 'financeAmount', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('76', '76', '154', '指旺汽车金融', '融资期数', '融资期数', 'periods', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('77', '77', '154', '指旺汽车金融', '租金（月）', '租金（月）', 'monthPay', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('78', '78', '154', '指旺汽车金融', '购置税', '购置税', 'purchaseTaxMoney', null, null, null, null, null, null, '439', null, null, null, null, null, '13');
INSERT INTO `user_reso` VALUES ('79', '79', '154', '指旺汽车金融', '路桥费', '路桥费', 'roadBridgeFee', null, null, null, null, null, null, '439', null, null, null, null, null, '14');
INSERT INTO `user_reso` VALUES ('80', '80', '154', '指旺汽车金融', '保险费', '保险费', 'annualAmount', null, null, null, null, null, null, '439', null, null, null, null, null, '15');
INSERT INTO `user_reso` VALUES ('81', '81', '154', '指旺汽车金融', 'GPS费', 'GPS费', 'gpsFee', null, null, null, null, null, null, '439', null, null, null, null, null, '16');
INSERT INTO `user_reso` VALUES ('82', '82', '154', '指旺汽车金融', '其他费用', '其他费用', 'otherFee', null, null, null, null, null, null, '439', null, null, null, null, null, '17');
INSERT INTO `user_reso` VALUES ('83', '83', '154', '指旺汽车金融', '状态', '状态', 'status', null, null, null, null, null, null, '439', null, null, null, null, null, '18');
INSERT INTO `user_reso` VALUES ('84', '84', '91', '指旺汽车金融', '文件名', '文件名', 'fileName', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('85', '85', '91', '指旺汽车金融', '上传时间', '上传时间', 'uploadTime', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('86', '86', '91', '指旺汽车金融', '操作人', '操作人', 'operatorName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('87', '87', '91', '指旺汽车金融', '备注', '备注', 'remark', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('88', '88', '180', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('89', '89', '180', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('90', '90', '180', '指旺汽车金融', '联系号码', '联系号码', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('91', '91', '180', '指旺汽车金融', '是否开户', '是否开户', 'isAccount', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('92', '92', '180', '指旺汽车金融', '绑卡银行', '绑卡银行', 'boundBank', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('93', '93', '180', '指旺汽车金融', '银行卡号', '银行卡号', 'bankCard', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('94', '94', '180', '指旺汽车金融', '客户号', '客户号', 'customId', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('95', '95', '180', '指旺汽车金融', '验卡失败原因', '验卡失败原因', 'faileReason', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('96', '96', '180', '指旺汽车金融', '结算通道', '结算通道', 'settlementChannel', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('97', '97', '184', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('98', '98', '184', '指旺汽车金融', '订单创建时间', '订单创建时间', 'orderCreateTime', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('99', '99', '184', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('100', '100', '184', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('101', '101', '184', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('102', '102', '184', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('103', '103', '184', '指旺汽车金融', '联系号码', '联系号码', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('104', '104', '184', '指旺汽车金融', '最近合同生成日期', '最近合同生成日期', 'latelyContractTime', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('105', '105', '192', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('106', '106', '192', '指旺汽车金融', '制单人', '制单人', 'recorderName', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('107', '107', '192', '指旺汽车金融', '所属部门', '所属部门', 'deptName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('108', '108', '192', '指旺汽车金融', '转交人', '转交人', 'transferName', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('109', '109', '192', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('110', '110', '192', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('111', '111', '192', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('112', '112', '192', '指旺汽车金融', '联系号码', '联系号码', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('113', '113', '192', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('114', '114', '192', '指旺汽车金融', '产品期数', '产品期数', 'periods', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('115', '115', '192', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('116', '116', '192', '指旺汽车金融', '审批状态', '审批状态', 'orderStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('117', '117', '235', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('118', '118', '235', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('119', '119', '235', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('120', '120', '235', '指旺汽车金融', '进入资源池时间', '进入资源池时间', 'intoPoolDate', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('121', '121', '235', '指旺汽车金融', '省份', '省份', 'province', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('122', '122', '235', '指旺汽车金融', '城市', '城市', 'city', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('123', '123', '235', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('124', '124', '235', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('125', '125', '235', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('126', '126', '235', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('127', '127', '235', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('128', '128', '244', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('129', '129', '244', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('130', '130', '244', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('131', '131', '244', '指旺汽车金融', '进入资源池时间', '进入资源池时间', 'intoPoolDate', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('132', '132', '244', '指旺汽车金融', '省份', '省份', 'province', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('133', '133', '244', '指旺汽车金融', '城市', '城市', 'city', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('134', '134', '244', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('135', '135', '244', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('136', '136', '244', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('137', '137', '244', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('138', '138', '244', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('139', '139', '253', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('140', '140', '253', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('141', '141', '253', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('142', '142', '253', '指旺汽车金融', '进入资源池时间', '进入资源池时间', 'intoPoolDate', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('143', '143', '253', '指旺汽车金融', '省份', '省份', 'province', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('144', '144', '253', '指旺汽车金融', '城市', '城市', 'city', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('145', '145', '253', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('146', '146', '253', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('147', '147', '253', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('148', '148', '253', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('149', '149', '253', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('150', '150', '262', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('151', '151', '262', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('152', '152', '262', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('153', '153', '262', '指旺汽车金融', '进入资源池时间', '进入资源池时间', 'intoPoolDate', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('154', '154', '262', '指旺汽车金融', '省份', '省份', 'province', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('155', '155', '262', '指旺汽车金融', '城市', '城市', 'city', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('156', '156', '262', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('157', '157', '262', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('158', '158', '262', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('159', '159', '262', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('160', '160', '262', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('161', '161', '271', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('162', '162', '271', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('163', '163', '271', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('164', '164', '271', '指旺汽车金融', '进入资源池时间', '进入资源池时间', 'intoPoolDate', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('165', '165', '271', '指旺汽车金融', '省份', '省份', 'province', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('166', '166', '271', '指旺汽车金融', '城市', '城市', 'city', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('167', '167', '271', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('168', '168', '271', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('169', '169', '271', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('170', '170', '271', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('171', '171', '271', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('172', '172', '280', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('173', '173', '280', '指旺汽车金融', '订单状态', '订单状态', 'orderStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('174', '174', '280', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('175', '175', '280', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('176', '176', '280', '指旺汽车金融', '领取时间', '领取时间', 'receiveDate', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('177', '177', '280', '指旺汽车金融', '处理时间', '处理时间', 'approvalDate', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('178', '178', '280', '指旺汽车金融', '省份', '省份', 'province', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('179', '179', '280', '指旺汽车金融', '城市', '城市', 'city', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('180', '180', '280', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('181', '181', '280', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('182', '182', '280', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('183', '183', '280', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('184', '184', '280', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '13');
INSERT INTO `user_reso` VALUES ('185', '185', '295', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('186', '186', '295', '指旺汽车金融', '订单状态', '订单状态', 'orderStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('187', '187', '295', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('188', '188', '295', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('189', '189', '295', '指旺汽车金融', '进入资源池时间', '进入资源池时间', 'intoPoolDate', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('190', '190', '295', '指旺汽车金融', '省份', '省份', 'province', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('191', '191', '295', '指旺汽车金融', '城市', '城市', 'city', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('192', '192', '295', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('193', '193', '295', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('194', '194', '295', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('195', '195', '295', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('196', '196', '295', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('197', '197', '304', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('198', '198', '304', '指旺汽车金融', '订单状态', '订单状态', 'orderStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('199', '199', '304', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('200', '200', '304', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('201', '201', '304', '指旺汽车金融', '进入资源池时间', '进入资源池时间', 'intoPoolDate', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('202', '202', '304', '指旺汽车金融', '省份', '省份', 'province', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('203', '203', '304', '指旺汽车金融', '城市', '城市', 'city', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('204', '204', '304', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('205', '205', '304', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('206', '206', '304', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('207', '207', '304', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('208', '208', '304', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('209', '209', '313', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('210', '210', '313', '指旺汽车金融', '订单状态', '订单状态', 'orderStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('211', '211', '313', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('212', '212', '313', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('213', '213', '313', '指旺汽车金融', '进入资源池时间', '进入资源池时间', 'intoPoolDate', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('214', '214', '313', '指旺汽车金融', '省份', '省份', 'province', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('215', '215', '313', '指旺汽车金融', '城市', '城市', 'city', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('216', '216', '313', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('217', '217', '313', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('218', '218', '313', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('219', '219', '313', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('220', '220', '313', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('221', '221', '322', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('222', '222', '322', '指旺汽车金融', '订单状态', '订单状态', 'orderStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('223', '223', '322', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('224', '224', '322', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('225', '225', '322', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('226', '226', '322', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('227', '227', '322', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('228', '228', '322', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('229', '229', '322', '指旺汽车金融', '订单归属公司', '订单归属公司', 'orderCompany', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('230', '230', '322', '指旺汽车金融', '归属部门', '归属部门', 'orderDept', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('231', '231', '322', '指旺汽车金融', '制单人', '制单人', 'recorder', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('232', '232', '331', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('233', '233', '331', '指旺汽车金融', '客户结算号', '客户结算号', 'clientNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('234', '234', '331', '指旺汽车金融', '客户姓名', '客户姓名', 'name', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('235', '235', '331', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('236', '236', '331', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('237', '237', '331', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('238', '238', '331', '指旺汽车金融', '合同生效日', '合同生效日', 'contractDate', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('239', '239', '331', '指旺汽车金融', '待还本金', '待还本金', 'principalReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('240', '240', '331', '指旺汽车金融', '待还利息', '待还利息', 'interestReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('241', '241', '331', '指旺汽车金融', '待还罚息', '待还罚息', 'penaltyReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('242', '242', '331', '指旺汽车金融', '利率%/月', '利率%/月', 'productRate', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('243', '243', '331', '指旺汽车金融', '结算通道', '结算通道', 'settlementChannel', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('244', '244', '331', '指旺汽车金融', '归属公司', '归属公司', 'companyChinaName', null, null, null, null, null, null, '439', null, null, null, null, null, '13');
INSERT INTO `user_reso` VALUES ('268', '268', '356', '指旺汽车金融', '审核时间', '审核时间', 'approvalDate', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('269', '269', '356', '指旺汽车金融', '省份', '省份', 'province', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('270', '270', '356', '指旺汽车金融', '城市', '城市', 'city', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('271', '271', '356', '指旺汽车金融', '网点', '网点', 'dot', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('272', '272', '356', '指旺汽车金融', '业务员', '业务员', 'salesmanName', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('273', '273', '356', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('274', '274', '356', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('275', '275', '356', '指旺汽车金融', '审核状态', '审核状态', 'approveStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('276', '276', '356', '指旺汽车金融', '是否提车', '是否提车', 'isDeliveryCar', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('277', '277', '356', '指旺汽车金融', '拒单原因', '拒单原因', 'refuseResource', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('278', '278', '356', '指旺汽车金融', '拒单细节', '拒单细节', 'refuseDetails', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('279', '279', '356', '指旺汽车金融', '备注', '备注', 'remark', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('280', '280', '356', '指旺汽车金融', '审核人员', '审核人员', 'approvalPersonal', null, null, null, null, null, null, '439', null, null, null, null, null, '13');
INSERT INTO `user_reso` VALUES ('281', '281', '376', '指旺汽车金融', '资料上传', '资料上传', 'isUploadFile', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('282', '282', '376', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('283', '283', '376', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('284', '284', '376', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('285', '285', '376', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('286', '286', '376', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('287', '287', '376', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('288', '288', '376', '指旺汽车金融', '联系号码', '联系号码', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('289', '289', '381', '指旺汽车金融', '处理状态', '处理状态', 'approvalDealStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('290', '290', '381', '指旺汽车金融', '处理时间', '处理时间', 'dealDate', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('291', '291', '381', '指旺汽车金融', '处理人', '处理人', 'dealerName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('292', '292', '381', '指旺汽车金融', '收款类型', '收款类型', 'applicationType', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('293', '293', '381', '指旺汽车金融', '收款金额', '收款金额', 'totalPayment', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('294', '294', '381', '指旺汽车金融', '收款账户名', '收款账户名', 'accountName', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('295', '295', '381', '指旺汽车金融', '申请日期', '申请日期', 'operatorTime', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('296', '296', '381', '指旺汽车金融', '申请人', '申请人', 'operatorName', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('297', '297', '390', '指旺汽车金融', '处理状态', '处理状态', 'processStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('298', '298', '390', '指旺汽车金融', '处理时间', '处理时间', 'processTime', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('299', '299', '390', '指旺汽车金融', '处理人', '处理人', 'processName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('300', '300', '390', '指旺汽车金融', '付款类型', '付款类型', 'refundType', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('301', '301', '390', '指旺汽车金融', '付款金额', '付款金额', 'refundTotalAmount', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('302', '302', '390', '指旺汽车金融', '客户账户名', '客户账户名', 'customerName', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('303', '303', '390', '指旺汽车金融', '开户银行', '开户银行', 'depositBank', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('304', '304', '390', '指旺汽车金融', '银行卡号', '银行卡号', 'cardNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('305', '305', '390', '指旺汽车金融', '申请日期', '申请日期', 'operateTime', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('306', '306', '390', '指旺汽车金融', '制单人', '制单人', 'operator', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('307', '307', '392', '指旺汽车金融', '文件名', '文件名', 'fileName', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('308', '308', '392', '指旺汽车金融', '上传时间', '上传时间', 'uploadTime', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('309', '309', '392', '指旺汽车金融', '操作人', '操作人', 'operatorName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('310', '310', '392', '指旺汽车金融', '备注', '备注', 'remark', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('311', '311', '399', '指旺汽车金融', '处理状态', '处理状态', 'collectMoneyDealStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('312', '312', '399', '指旺汽车金融', '处理时间', '处理时间', 'dealTime', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('313', '313', '399', '指旺汽车金融', '处理人', '处理人', 'dealerName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('314', '314', '399', '指旺汽车金融', '收款类型', '收款类型', 'applicationType', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('315', '315', '399', '指旺汽车金融', '收款总金额', '收款总金额', 'totalPayment', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('316', '316', '399', '指旺汽车金融', '收款账户名', '收款账户名', 'accountName', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('317', '317', '399', '指旺汽车金融', '申请日期', '申请日期', 'operatorTime', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('318', '318', '399', '指旺汽车金融', '申请人', '申请人', 'operatorName', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('319', '319', '405', '指旺汽车金融', '处理状态', '处理状态', 'processStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('320', '320', '405', '指旺汽车金融', '处理时间', '处理时间', 'processTime', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('321', '321', '405', '指旺汽车金融', '处理人', '处理人', 'processName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('322', '322', '405', '指旺汽车金融', '付款类型', '付款类型', 'refundType', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('323', '323', '405', '指旺汽车金融', '付款总金额', '付款总金额', 'refundTotalAmount', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('324', '324', '405', '指旺汽车金融', '付款账户名', '付款账户名', 'customerName', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('325', '325', '405', '指旺汽车金融', '申请日期', '申请日期', 'operateTime', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('326', '326', '405', '指旺汽车金融', '制单人', '制单人', 'operator', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('327', '327', '412', '指旺汽车金融', '订单号', '订单号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('328', '328', '412', '指旺汽车金融', '客户结算号', '客户结算号', 'clientNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('329', '329', '412', '指旺汽车金融', '客户姓名', '客户姓名', 'name', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('330', '330', '412', '指旺汽车金融', '证件号', '证件号', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('331', '331', '412', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('332', '332', '412', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('333', '333', '412', '指旺汽车金融', '合同生效日', '合同生效日', 'contractDate', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('334', '334', '412', '指旺汽车金融', '待还本金', '待还本金', 'principalReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('335', '335', '412', '指旺汽车金融', '待还利息', '待还利息', 'interestReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('336', '336', '412', '指旺汽车金融', '待还罚息', '待还罚息', 'penaltyReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('337', '337', '412', '指旺汽车金融', '利率%/月', '利率%/月', 'productRate', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('338', '338', '412', '指旺汽车金融', '结算通道', '结算通道', 'settlementChannel', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('339', '339', '412', '指旺汽车金融', '归属公司', '归属公司', 'companyChinaName', null, null, null, null, null, null, '439', null, null, null, null, null, '13');
INSERT INTO `user_reso` VALUES ('340', '340', '420', '指旺汽车金融', '订单号', '订单号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('341', '341', '420', '指旺汽车金融', '客户结算号', '客户结算号', 'clientNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('342', '342', '420', '指旺汽车金融', '客户姓名', '客户姓名', 'name', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('343', '343', '420', '指旺汽车金融', '证件号', '证件号', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('344', '344', '420', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('345', '345', '420', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('346', '346', '420', '指旺汽车金融', '合同生效日', '合同生效日', 'contractDate', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('347', '347', '420', '指旺汽车金融', '待还本金', '待还本金', 'principalReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('348', '348', '420', '指旺汽车金融', '待还利息', '待还利息', 'interestReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('349', '349', '420', '指旺汽车金融', '待还罚息', '待还罚息', 'penaltyReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('350', '350', '420', '指旺汽车金融', '利率%/月', '利率%/月', 'productRate', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('351', '351', '420', '指旺汽车金融', '结算通道', '结算通道', 'settlementChannel', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('352', '352', '420', '指旺汽车金融', '归属公司', '归属公司', 'companyChinaName', null, null, null, null, null, null, '439', null, null, null, null, null, '13');
INSERT INTO `user_reso` VALUES ('353', '353', '428', '指旺汽车金融', '订单号', '订单号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('354', '354', '428', '指旺汽车金融', '客户结算号', '客户结算号', 'clientNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('355', '355', '428', '指旺汽车金融', '客户姓名', '客户姓名', 'name', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('356', '356', '428', '指旺汽车金融', '证件号', '证件号', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('357', '357', '428', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('358', '358', '428', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('359', '359', '428', '指旺汽车金融', '合同生效日', '合同生效日', 'contractDate', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('360', '360', '428', '指旺汽车金融', '结算通道', '结算通道', 'settlementChannel', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('361', '361', '428', '指旺汽车金融', '归属公司', '归属公司', 'companyChinaName', null, null, null, null, null, null, '439', null, null, null, null, null, '13');
INSERT INTO `user_reso` VALUES ('362', '362', '435', '指旺汽车金融', '订单号', '订单号', 'orderId', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('363', '363', '435', '指旺汽车金融', '客户结算号', '客户结算号', 'clientNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('364', '364', '435', '指旺汽车金融', '客户姓名', '客户姓名', 'customerName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('365', '365', '435', '指旺汽车金融', '证件号', '证件号', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('366', '366', '435', '指旺汽车金融', '手机号', '手机号', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('367', '367', '435', '指旺汽车金融', '合同生效日', '合同生效日', 'contractDate', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('368', '368', '435', '指旺汽车金融', '结清日期', '结清日期', 'settlementDay', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('369', '369', '435', '指旺汽车金融', '利率%/月', '利率%/月', 'productRate', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('370', '370', '435', '指旺汽车金融', '结算通道', '结算通道', 'settlementChannel', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('371', '371', '435', '指旺汽车金融', '结清状态', '结清状态', 'settlementType', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('372', '372', '435', '指旺汽车金融', '归属公司', '归属公司', 'companyChinaName', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('373', '373', '447', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('374', '374', '447', '指旺汽车金融', '收款类型', '收款类型', 'applicationType', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('375', '375', '447', '指旺汽车金融', '申请状态', '申请状态', 'approvalStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('376', '376', '447', '指旺汽车金融', '收款客户名', '收款客户名', 'accountName', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('377', '377', '447', '指旺汽车金融', '收款金额', '收款金额', 'totalPayment', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('378', '378', '447', '指旺汽车金融', '申请时间', '申请时间', 'operatorTime', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('379', '379', '447', '指旺汽车金融', '制单人', '制单人', 'userUserName', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('380', '380', '455', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('381', '381', '455', '指旺汽车金融', '付款类型', '付款类型', 'refundType', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('382', '382', '455', '指旺汽车金融', '申请状态', '申请状态', 'applicationStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('383', '383', '455', '指旺汽车金融', '付款客户名', '付款客户名', 'customerName', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('384', '384', '455', '指旺汽车金融', '付款金额', '付款金额', 'refundTotalAmount', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('385', '385', '455', '指旺汽车金融', '申请时间', '申请时间', 'operateTime', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('386', '386', '455', '指旺汽车金融', '制单人', '制单人', 'operator', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('387', '387', '456', '指旺汽车金融', '开户日期', '开户日期', 'openAccountDate', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('388', '388', '456', '指旺汽车金融', '开户类型', '开户类型', 'accountType', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('389', '389', '456', '指旺汽车金融', '客户号', '客户号', 'clientNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('390', '390', '456', '指旺汽车金融', '客户姓名', '客户姓名', 'name', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('391', '391', '456', '指旺汽车金融', '证件号码', '证件号码', 'certificateNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('392', '392', '456', '指旺汽车金融', '预留手机', '预留手机', 'reservedPhoneNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('393', '393', '463', '指旺汽车金融', '出账日期', '出账日期', 'paymentDate', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('394', '394', '463', '指旺汽车金融', '出账客户号', '出账客户号', 'clientNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('395', '395', '463', '指旺汽车金融', '出账卡号', '出账卡号', 'cardNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('396', '396', '463', '指旺汽车金融', '客户姓名', '客户姓名', 'clientName', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('397', '397', '463', '指旺汽车金融', '支付银行', '支付银行', 'depositBank', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('398', '398', '463', '指旺汽车金融', '支付金额', '支付金额', 'paymentAmount', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('399', '399', '463', '指旺汽车金融', '订单号', '订单号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('400', '400', '463', '指旺汽车金融', '交易状态', '交易状态', 'tradingStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('401', '401', '463', '指旺汽车金融', '失败原因', '失败原因', 'failReason', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('402', '402', '463', '指旺汽车金融', '操作人', '操作人', 'operateName', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('403', '403', '48', '指旺汽车金融', '客户姓名', '客户姓名', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('404', '404', '48', '指旺汽车金融', '环节', '环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('405', '405', '48', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('406', '406', '48', '指旺汽车金融', '联系号码', '联系号码', 'mobileMain', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('407', '407', '48', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('408', '408', '48', '指旺汽车金融', '订单编号', '订单编号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('409', '409', '48', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('410', '410', '48', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('411', '411', '48', '指旺汽车金融', '产品期数', '产品期数', 'periods', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('412', '412', '48', '指旺汽车金融', '利率（月）', '利率（月）', 'productRate', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('413', '413', '48', '指旺汽车金融', '还款方式', '还款方式', 'payWay', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('414', '414', '48', '指旺汽车金融', '融资总额', '融资总额', 'financingAmount', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('415', '415', '48', '指旺汽车金融', '订单状态', '订单状态', 'orderStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '13');
INSERT INTO `user_reso` VALUES ('416', '416', '9', '指旺汽车金融', '数据权限', '数据权限', 'userManager', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('417', '417', '466', '指旺汽车金融', '订单号', '订单号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('418', '418', '466', '指旺汽车金融', '订单创建时间', '订单创建时间', 'createTime', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('419', '419', '466', '指旺汽车金融', '客户', '客户', 'personalName', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('420', '420', '466', '指旺汽车金融', '订单类型', '订单类型', 'orderType', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('421', '421', '466', '指旺汽车金融', '产品名称', '产品名称', 'productName', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('422', '422', '466', '指旺汽车金融', '产品期数', '产品期数', 'periods', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('423', '423', '466', '指旺汽车金融', '利率(月)', '利率(月)', 'productRate', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('424', '424', '466', '指旺汽车金融', '还款方式', '还款方式', 'payWay', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('425', '425', '466', '指旺汽车金融', '融资总额', '融资总额', 'financingAmount', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('427', '427', '466', '指旺汽车金融', '订单状态', '订单状态', 'orderStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('428', '428', '340', '指旺汽车金融', '减免金额', '减免金额', 'remitAmount', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('429', '429', '340', '指旺汽车金融', '减免期数', '减免期数', 'periods', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('430', '430', '340', '指旺汽车金融', '订单环节', '订单环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('431', '431', '340', '指旺汽车金融', '订单状态', '订单状态', 'orderStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('432', '432', '340', '指旺汽车金融', '申请时间', '申请时间', 'applyDate', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('433', '433', '340', '指旺汽车金融', '客户姓名', '客户姓名', 'name', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('434', '434', '340', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('435', '435', '340', '指旺汽车金融', '手机号', '手机号', 'mobileNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('436', '436', '340', '指旺汽车金融', '订单创建时间', '订单创建时间', 'orderCreateTime', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('437', '437', '340', '指旺汽车金融', '合同生效日期', '合同生效日期', 'contractDate', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('438', '438', '340', '指旺汽车金融', '备注', '备注', 'remitRemark', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('439', '439', '340', '指旺汽车金融', '订单号', '订单号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('440', '440', '348', '指旺汽车金融', ' ', '冻结金额', 'remitAmount', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('441', '441', '348', '指旺汽车金融', '冻结期数', '冻结期数', 'periods', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
INSERT INTO `user_reso` VALUES ('442', '442', '348', '指旺汽车金融', '订单环节', '订单环节', 'orderLink', null, null, null, null, null, null, '439', null, null, null, null, null, '3');
INSERT INTO `user_reso` VALUES ('443', '443', '348', '指旺汽车金融', '订单状态', '订单状态', 'orderStatus', null, null, null, null, null, null, '439', null, null, null, null, null, '4');
INSERT INTO `user_reso` VALUES ('444', '444', '348', '指旺汽车金融', '申请时间', '申请时间', 'applyDate', null, null, null, null, null, null, '439', null, null, null, null, null, '5');
INSERT INTO `user_reso` VALUES ('445', '445', '348', '指旺汽车金融', '客户姓名', '客户姓名', 'name', null, null, null, null, null, null, '439', null, null, null, null, null, '6');
INSERT INTO `user_reso` VALUES ('446', '446', '348', '指旺汽车金融', '证件号码', '证件号码', 'idCard', null, null, null, null, null, null, '439', null, null, null, null, null, '7');
INSERT INTO `user_reso` VALUES ('447', '447', '348', '指旺汽车金融', '手机号', '手机号', 'mobileNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '8');
INSERT INTO `user_reso` VALUES ('448', '448', '348', '指旺汽车金融', '订单创建时间', '订单创建时间', 'orderCreateTime', null, null, null, null, null, null, '439', null, null, null, null, null, '9');
INSERT INTO `user_reso` VALUES ('449', '449', '348', '指旺汽车金融', '合同生效日期', '合同生效日期', 'contractDate', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('450', '450', '348', '指旺汽车金融', '订单号', '订单号', 'orderNumber', null, null, null, null, null, null, '439', null, null, null, null, null, '11');
INSERT INTO `user_reso` VALUES ('451', '451', '348', '指旺汽车金融', '备注', '备注', 'remitRemark', null, null, null, null, null, null, '439', null, null, null, null, null, '12');
INSERT INTO `user_reso` VALUES ('452', '452', '466', '指旺汽车金融', '环节', '环节', 'orderLink\r\n', null, null, null, null, null, null, '439', null, null, null, null, null, '10');
INSERT INTO `user_reso` VALUES ('453', '453', '412', '指旺汽车金融', '待还管理费', '待还管理费', 'manageFeeReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '14');
INSERT INTO `user_reso` VALUES ('454', '454', '412', '指旺汽车金融', '待还总金额', '待还总金额', 'sumReceivable', null, null, null, null, null, null, '439', null, null, null, null, null, '15');
INSERT INTO `user_reso` VALUES ('455', '455', '474', '指旺汽车金融', '模板名称', '模板名称', 'templateName', null, null, null, null, null, null, '439', null, null, null, null, null, '1');
INSERT INTO `user_reso` VALUES ('456', '456', '474', '指旺汽车金融', '创建人', '创建人', 'operator', null, null, null, null, null, null, '439', null, null, null, null, null, '2');
